spring:
  application:
    name: PaymentService

  datasource:
    url: jdbc:mysql://localhost:3306/paymentDB
    username: root
    password: Pere@718
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
     ddl-auto: update
     
server.port: 9093