apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  selector:
    app: mongo
  type: NodePort
  ports: 
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32000 