apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
      - name: book-app
        image: pererosh/bookapp:v4
        ports:
        - containerPort: 8080
        env:
          - name: MYSQL_HOST
            value: mysql
          - name: MYSQL_ROOT_PASSWORD
            value: pereroot
          - name: MYSQL_DATABASE
            value: command_db
          - name: MYSQL_USER
            value: admin
          - name: MYSQL_PASSWORD
            value: admin@123 

---
apiVersion: v1
kind: Service
metadata:
  name: book-app
  labels:
    name: book-app
spec:
  selector:
    app: book-app
  type: NodePort
  ports:
    - nodePort: 30163
      port: 8080        
      targetPort: 8080
      protocol: TCP
      
      