apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-api
  template:
    metadata:
      name: nginx-api-pod #podName
      labels:
        app: nginx-api #podLabel
    spec:
      # nodeName: multinode-m02
      # nodeSelector:
      #   team: analytics
      tolerations:
      - key: "env"
        operator: "Equal"
        value: "production"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: rank
                    operator: Lt
                    values:
                      - "4"
        # podAntiAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #     - labelSelector:
        #         matchExpressions:
        #         - key: app
        #           operator: In
        #           values:
        #           - "nginx"
        #       topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx-api-container #containerName
        image: nginx:alpine
        ports:
        - containerPort: 8082