apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-service
  template:
    metadata:
      name: command-service-pod
      labels:
        app: command-service
    spec:
      containers:
      - name: command-service-container
        image: pererosh/product-command:v2
        ports:
        - containerPort: 9191
        env:
          - name: MYSQL_HOST
            value: mysql-command
          - name: MYSQL_ROOT_PASSWORD
            value: pereroot
          - name: MYSQL_DATABASE
            value: command_db
          - name: MYSQL_USER
            value: admin
          - name: MYSQL_PASSWORD
            value: admin@123 

---
apiVersion: v1
kind: Service
metadata:
  name: command-service
spec:
  selector:
    app: command-service
  ports:
    - name: command-service
      port: 9191      
      targetPort: 9191